title: SRS x InstaLILY Summit Hackathon
description: Complete guide to building AI agents with Google's ADK framework
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Site settings
baseurl: "" 
url: ""

# Features
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Appearance
heading_anchors: true
aux_links:
  "GitHub":
    - "//github.com/google/adk"
  "ADK Docs":
    - "//google.github.io/adk-docs/"

# Footer
footer_content: "SRS x InstaLILY Summit Hackathon 2024. Built with ❤️ using Jekyll and Just the Docs."

# Back to top
back_to_top: true
back_to_top_text: "Back to top"

# Code copying
enable_copy_code_button: true

# Callouts
callouts:
  warning:
    color: red
  important:
    color: yellow
  note:
    color: blue
  tip:
    color: green
